version: "1.0"

services:
  server:
    image: videochat
    deploy:
      replicas: 1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"
    ports: -8081:8081
    command: --addr :8081
